---
title: "RNA-Seq_differential_expression_analysis"
output: html_document
date: "2025-04-18"
---

```{r,packages}


suppressPackageStartupMessages({
  library("EnhancedVolcano")
  library("limma")
  library("tximport")
  library("apeglm")
  library("eulerr")
library("DESeq2")
  library("HGNChelper")
  library("tictoc")
  library("DESeq2")
  library("kableExtra")
  library("beeswarm")
  library("missMethyl")
  library("gridExtra")
  library("png")
  library("metafor")
  library("ggplot2")
  library("purrr")
library("metafor")
library("dplyr")
library("readxl")
library("ggplot2")
library("tidyverse")
library("magrittr")
library("readr")
library("eulerr")
library("RColorBrewer")
library("e1071")
  library("plotly") 
  library("pheatmap")

})

CORES=8

```
# Read the sample manifest and alignment summary

# Confirm all your pseudo-alignment rates are comfortably high (> ~90%).

```{r}
samples <- read_tsv("/mnt/vol1/RNA-Seq/kallisto_tutorial/results/samples.txt", col_types = cols())
samples

align <- read_tsv("/mnt/vol1/RNA-Seq/kallisto_tutorial/results/alignment_summary.tsv")
align %>% 
  dplyr::arrange(align$`Rate(%)`) %>% 
  print(n=10)

```

# 

```{r fig.width=11, fig.height=9, message=FALSE, warning=FALSE, echo=TRUE}

tx2gene <- read_tsv("/mnt/vol1/RNA-Seq/kallisto_tutorial/results/tx2gene.tsv",
                    col_names = c("TXNAME","GENEID"),
                    col_types = cols(
                      TXNAME = col_character(),
                      GENEID = col_character()
                    ))

head(tx2gene)

files <- samples$path
names(files) <- samples$sample

txi <- tximport(files    = files,
                type     = "kallisto",
                tx2gene  = tx2gene,
                ignoreTxVersion = TRUE)

# Inspect the components:
names(txi)

```


```{r zscore_female}

pheno<-read_delim("/mnt/vol1/RNA-Seq/SraRunTable.csv")
coldata <- pheno %>%
  select(sample = Run, condition = treatment) 

coldata <- coldata %>%
  mutate(condition = dplyr::recode(condition, 
                            "None" = "Control", 
                            "7day_UUO" = "Treated"))

samples <- left_join(samples, coldata, by = "sample")

```



```{r}
all(samples$sample == colnames(txi$counts))
samples <- samples[match(colnames(txi$counts), samples$sample), ]

coldata <- samples %>%
  column_to_rownames("sample") %>%
  select(condition)

dds <- DESeqDataSetFromTximport(txi,
                                colData = coldata,
                                design  = ~ condition)
dds_1 <- DESeq(dds)
res <- results(dds_1, contrast = c("condition","Treated","Control"))
summary(res)
```



```{r}
keep <- rowSums(counts(dds)) >= 10
dds_2  <- dds[keep, ]
dds_3 <- DESeq(dds_2)
res_1 <- results(dds_3, contrast = c("condition","Treated","Control"))
summary(res_1)

sum(res_1$padj < 0.05, na.rm=TRUE)

```
#Apply LFC shrinkage (for ranking)


```{r}

resLFC <- lfcShrink(dds_3,
                    coef = "condition_Treated_vs_Control",
                    type = "apeglm")
vsd <- vst(dds_3, blind = FALSE)
plotPCA(vsd, intgroup="condition") + ggtitle("PCA: Treated vs Control")

dist_mat <- dist(t(assay(vsd)))
pheatmap(as.matrix(dist_mat),
         clustering_distance_rows = dist_mat,
         clustering_distance_cols = dist_mat,
         main = "Sample distances")

EnhancedVolcano(resLFC,
                lab = rownames(resLFC),
                x = 'log2FoldChange',
                y = 'padj',
                title = 'Treated vs Control')

```


```{r}





```









